//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicaBiometrics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NicaBiometrics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nica Biometrics.
        /// </summary>
        internal static string LABEL_APP_NAME {
            get {
                return ResourceManager.GetString("LABEL_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is running in the background..
        /// </summary>
        internal static string LABEL_APPLICATION_RUNNING_BACKGROUND {
            get {
                return ResourceManager.GetString("LABEL_APPLICATION_RUNNING_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *deviceid, commkey cannot be null !.
        /// </summary>
        internal static string LABEL_COMM_KEY_REQUIRED {
            get {
                return ResourceManager.GetString("LABEL_COMM_KEY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you to exit application?.
        /// </summary>
        internal static string LABEL_CONFIRM_EXIT {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connected!.
        /// </summary>
        internal static string LABEL_DEVICE_CONNECTED {
            get {
                return ResourceManager.GetString("LABEL_DEVICE_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to device. Check your IP Address or port..
        /// </summary>
        internal static string LABEL_DEVICE_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("LABEL_DEVICE_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is disconnected!.
        /// </summary>
        internal static string LABEL_DISCONNECT_WITH_DEVICE {
            get {
                return ResourceManager.GetString("LABEL_DISCONNECT_WITH_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *CommKey illegal!.
        /// </summary>
        internal static string LABEL_ILLEGAL_COMMKEY {
            get {
                return ResourceManager.GetString("LABEL_ILLEGAL_COMMKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Device illegal!.
        /// </summary>
        internal static string LABEL_ILLEGAL_DEVICE {
            get {
                return ResourceManager.GetString("LABEL_ILLEGAL_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device IP address.
        /// </summary>
        internal static string LABEL_INVALID_DEVICE_IP_ADDRESS {
            get {
                return ResourceManager.GetString("LABEL_INVALID_DEVICE_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No biometric device found..
        /// </summary>
        internal static string LABEL_NO_USB_DEVICE_FOUND {
            get {
                return ResourceManager.GetString("LABEL_NO_USB_DEVICE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string LABEL_SAVE {
            get {
                return ResourceManager.GetString("LABEL_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the device, ErrorCode=.
        /// </summary>
        internal static string LABEL_UNABLE_TO_CONNECT_VIA_USB {
            get {
                return ResourceManager.GetString("LABEL_UNABLE_TO_CONNECT_VIA_USB", resourceCulture);
            }
        }
    }
}
