//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicaBiometrics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NicaBiometrics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nica Biometrics.
        /// </summary>
        internal static string LABEL_APP_NAME {
            get {
                return ResourceManager.GetString("LABEL_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is running in the background..
        /// </summary>
        internal static string LABEL_APPLICATION_RUNNING_BACKGROUND {
            get {
                return ResourceManager.GetString("LABEL_APPLICATION_RUNNING_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometrics.
        /// </summary>
        internal static string LABEL_BIOMETRICS {
            get {
                return ResourceManager.GetString("LABEL_BIOMETRICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LABEL_CANCEL {
            get {
                return ResourceManager.GetString("LABEL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation.
        /// </summary>
        internal static string LABEL_CANCEL_OPERATION {
            get {
                return ResourceManager.GetString("LABEL_CANCEL_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear logs.
        /// </summary>
        internal static string LABEL_CLEAR_LOGS {
            get {
                return ResourceManager.GetString("LABEL_CLEAR_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *deviceid, commkey cannot be null !.
        /// </summary>
        internal static string LABEL_COMM_KEY_REQUIRED {
            get {
                return ResourceManager.GetString("LABEL_COMM_KEY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string LABEL_COMPANY {
            get {
                return ResourceManager.GetString("LABEL_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you to exit application?.
        /// </summary>
        internal static string LABEL_CONFIRM_EXIT {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to device....
        /// </summary>
        internal static string LABEL_CONNECTING_TO_DEVICE {
            get {
                return ResourceManager.GetString("LABEL_CONNECTING_TO_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connected!.
        /// </summary>
        internal static string LABEL_DEVICE_CONNECTED {
            get {
                return ResourceManager.GetString("LABEL_DEVICE_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to device. Check your IP Address or port..
        /// </summary>
        internal static string LABEL_DEVICE_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("LABEL_DEVICE_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        internal static string LABEL_DEVICE_NAME {
            get {
                return ResourceManager.GetString("LABEL_DEVICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string LABEL_DISABLE {
            get {
                return ResourceManager.GetString("LABEL_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is disconnected!.
        /// </summary>
        internal static string LABEL_DISCONNECT_WITH_DEVICE {
            get {
                return ResourceManager.GetString("LABEL_DISCONNECT_WITH_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting device....
        /// </summary>
        internal static string LABEL_DISCONNECTING_DEVICE {
            get {
                return ResourceManager.GetString("LABEL_DISCONNECTING_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee URL.
        /// </summary>
        internal static string LABEL_EMPLOYEE_URL {
            get {
                return ResourceManager.GetString("LABEL_EMPLOYEE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string LABEL_ENABLE {
            get {
                return ResourceManager.GetString("LABEL_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing a connection to the server....
        /// </summary>
        internal static string LABEL_ESTABLISHING_SERVER_CONNECTION {
            get {
                return ResourceManager.GetString("LABEL_ESTABLISHING_SERVER_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *CommKey illegal!.
        /// </summary>
        internal static string LABEL_ILLEGAL_COMMKEY {
            get {
                return ResourceManager.GetString("LABEL_ILLEGAL_COMMKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Device illegal!.
        /// </summary>
        internal static string LABEL_ILLEGAL_DEVICE {
            get {
                return ResourceManager.GetString("LABEL_ILLEGAL_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Port illegal!.
        /// </summary>
        internal static string LABEL_ILLEGAL_PORT {
            get {
                return ResourceManager.GetString("LABEL_ILLEGAL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device IP address.
        /// </summary>
        internal static string LABEL_INVALID_DEVICE_IP_ADDRESS {
            get {
                return ResourceManager.GetString("LABEL_INVALID_DEVICE_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac address.
        /// </summary>
        internal static string LABEL_MAC_ADDRESS {
            get {
                return ResourceManager.GetString("LABEL_MAC_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *No data from terminal returns!.
        /// </summary>
        internal static string LABEL_NO_DATA_TERMINAL {
            get {
                return ResourceManager.GetString("LABEL_NO_DATA_TERMINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fingerprint device found..
        /// </summary>
        internal static string LABEL_NO_USB_DEVICE_FOUND {
            get {
                return ResourceManager.GetString("LABEL_NO_USB_DEVICE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing server connection....
        /// </summary>
        internal static string LABEL_REFRESHING_SERVER_CONNECTION {
            get {
                return ResourceManager.GetString("LABEL_REFRESHING_SERVER_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *RegEvent failed,ErrorCode: .
        /// </summary>
        internal static string LABEL_REG_EVENT_FAILED {
            get {
                return ResourceManager.GetString("LABEL_REG_EVENT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered events.
        /// </summary>
        internal static string LABEL_REGISTERED_EVENTS {
            get {
                return ResourceManager.GetString("LABEL_REGISTERED_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        internal static string LABEL_REMOTE {
            get {
                return ResourceManager.GetString("LABEL_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string LABEL_RESTART {
            get {
                return ResourceManager.GetString("LABEL_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is restarting....
        /// </summary>
        internal static string LABEL_RESTARTING_DEVICE {
            get {
                return ResourceManager.GetString("LABEL_RESTARTING_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string LABEL_SAVE {
            get {
                return ResourceManager.GetString("LABEL_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string LABEL_SERIAL {
            get {
                return ResourceManager.GetString("LABEL_SERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string LABEL_SHUTDOWN {
            get {
                return ResourceManager.GetString("LABEL_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down device....
        /// </summary>
        internal static string LABEL_SHUTTING_DOWN {
            get {
                return ResourceManager.GetString("LABEL_SHUTTING_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string LABEL_START {
            get {
                return ResourceManager.GetString("LABEL_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting device....
        /// </summary>
        internal static string LABEL_STARTING_DEVICE {
            get {
                return ResourceManager.GetString("LABEL_STARTING_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in URL.
        /// </summary>
        internal static string LABEL_TIME_IN_URL {
            get {
                return ResourceManager.GetString("LABEL_TIME_IN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out URL.
        /// </summary>
        internal static string LABEL_TIME_OUT_URL {
            get {
                return ResourceManager.GetString("LABEL_TIME_OUT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the network. ErrorCode=.
        /// </summary>
        internal static string LABEL_UNABLE_TO_CONNECT_VIA_NET {
            get {
                return ResourceManager.GetString("LABEL_UNABLE_TO_CONNECT_VIA_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the device. ErrorCode=.
        /// </summary>
        internal static string LABEL_UNABLE_TO_CONNECT_VIA_USB {
            get {
                return ResourceManager.GetString("LABEL_UNABLE_TO_CONNECT_VIA_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update employee records.
        /// </summary>
        internal static string LABEL_UPDATE_EMPLOYEE_RECORD {
            get {
                return ResourceManager.GetString("LABEL_UPDATE_EMPLOYEE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked out employee id: .
        /// </summary>
        internal static string MESESAGE_CHECKED_OUT {
            get {
                return ResourceManager.GetString("MESESAGE_CHECKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckedIn employee id: .
        /// </summary>
        internal static string MESSAGE_CHECKED_IN {
            get {
                return ResourceManager.GetString("MESSAGE_CHECKED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to checked out employee id: .
        /// </summary>
        internal static string MESSAGE_FAILED_TO_CHECKED_OUT {
            get {
                return ResourceManager.GetString("MESSAGE_FAILED_TO_CHECKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to checked In employee id: .
        /// </summary>
        internal static string MESSAGE_FAILED_TO_CHEKED_IN {
            get {
                return ResourceManager.GetString("MESSAGE_FAILED_TO_CHEKED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get company.
        /// </summary>
        internal static string MESSAGE_FAILED_TO_GET_COMPANY {
            get {
                return ResourceManager.GetString("MESSAGE_FAILED_TO_GET_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish connection.
        /// </summary>
        internal static string MESSAGE_INVALID_SERVER_ADDRESS {
            get {
                return ResourceManager.GetString("MESSAGE_INVALID_SERVER_ADDRESS", resourceCulture);
            }
        }
    }
}
